### ISSUE TITLE
error: Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by didac-adria** [trufi-association/arb-convert#2]
Hello guys!

Great package, we like it! We have an issue though with the package, using the arb2po part. It's a problem when adding a new translation string.

We make this:
`arb2po --sourcefile intl_messages.arb --targetfile ninja_es.arb --out ninja_es.po`
Where our source file is the arb resulting from the intl_translation package from dart. Therefore, when adding a new string to be translated, this file includes such message but our target file (containing the already translated strings) doesn't. Thus, we get this error:

> error: Cannot read property 'replace' of undefined

Thanks guys!

**Comment by mdoelker** [comment]
Hi,

ah I see, I'll have a look asap.

Thanks for the report!

**Comment by mdoelker** [comment]
Fixed in v1.1.2

**Comment by didac-adria** [comment]
Super!

Thanks a lot! We'll test it!
